# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [2]:
df = pd.read_csv("AviationData.csv", encoding="utf-8", encoding_errors="replace")

print(df.shape)
print(df.info())
print(df.describe(include="all"))

df.isna().sum()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14144\1188867872.py:1: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("AviationData.csv", encoding="utf-8", encoding_errors="replace")

(88889, 31)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB
None
              Event.Id Investigation.Type Accident.Number  Event.Date  \
count            88889              88889           88889       88889
unique           87951                  2           88863       14782
top     20001212X19172           Accident      CEN22LA149  1984-06-30
freq                 3              85015               2          25
mean               NaN                NaN             NaN         NaN
std                NaN                NaN             NaN         NaN
min                NaN                NaN             NaN         NaN
25%                NaN                NaN             NaN         NaN
50%                NaN                NaN             NaN         NaN
75%                NaN                NaN             NaN         NaN
max                NaN                NaN             NaN         NaN

             Location        Country Latitude Longitude Airport.Code  \
count           88837          88663    34382     34373        50132
unique          27758            219    25592     27156        10374
top     ANCHORAGE, AK  United States  332739N  0112457W         NONE
freq              434          82248       19        24         1488
mean              NaN            NaN      NaN       NaN          NaN
std               NaN            NaN      NaN       NaN          NaN
min               NaN            NaN      NaN       NaN          NaN
25%               NaN            NaN      NaN       NaN          NaN
50%               NaN            NaN      NaN       NaN          NaN
75%               NaN            NaN      NaN       NaN          NaN
max               NaN            NaN      NaN       NaN          NaN

       Airport.Name  ... Purpose.of.flight Air.carrier Total.Fatal.Injuries  \
count         52704  ...             82697       16648         77488.000000
unique        24870  ...                26       13590                  NaN
top         Private  ...          Personal       Pilot                  NaN
freq            240  ...             49448         258                  NaN
mean            NaN  ...               NaN         NaN             0.647855
std             NaN  ...               NaN         NaN             5.485960
min             NaN  ...               NaN         NaN             0.000000
25%             NaN  ...               NaN         NaN             0.000000
50%             NaN  ...               NaN         NaN             0.000000
75%             NaN  ...               NaN         NaN             0.000000
max             NaN  ...               NaN         NaN           349.000000

       Total.Serious.Injuries Total.Minor.Injuries Total.Uninjured  \
count            76379.000000         76956.000000    82977.000000
unique                    NaN                  NaN             NaN
top                       NaN                  NaN             NaN
freq                      NaN                  NaN             NaN
mean                 0.279881             0.357061        5.325440
std                  1.544084             2.235625       27.913634
min                  0.000000             0.000000        0.000000
25%                  0.000000             0.000000        0.000000
50%                  0.000000             0.000000        1.000000
75%                  0.000000             0.000000        2.000000
max                161.000000           380.000000      699.000000

       Weather.Condition  Broad.phase.of.flight   Report.Status  \
count              84397                  61724           82505
unique                 4                     12           17074
top                  VMC                Landing  Probable Cause
freq               77303                  15428           61754
mean                 NaN                    NaN             NaN
std                  NaN                    NaN             NaN
min                  NaN                    NaN             NaN
25%                  NaN                    NaN             NaN
50%                  NaN                    NaN             NaN
75%                  NaN                    NaN             NaN
max                  NaN                    NaN             NaN

       Publication.Date
count             75118
unique             2924
top          25-09-2020
freq              17019
mean                NaN
std                 NaN
min                 NaN
25%                 NaN
50%                 NaN
75%                 NaN
max                 NaN

[11 rows x 31 columns]

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [3]:
# filter by age to get keep accidents from 1983 onwards
df["Event.Date"] = pd.to_datetime(df["Event.Date"], errors="coerce")
df["Event.Year"] = df["Event.Date"].dt.year
df = df[df["Event.Year"] >= 1983]
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Event.Year
3600,20001214X42040,Accident,LAX83LA093,1983-01-01,"ARROYO GRANDE, CA",United States,NaN,NaN,NaN,NaN,...,NaN,0.0,1.0,0.0,1.0,VMC,Landing,Probable Cause,NaN,1983
3601,20001214X42095,Accident,SEA83LA036,1983-01-01,"NEWPORT, OR",United States,NaN,NaN,ONP,NEWPORT MUNICIPAL,...,NaN,0.0,0.0,1.0,3.0,VMC,Approach,Probable Cause,NaN,1983
3602,20001214X42067,Accident,MKC83LA056,1983-01-01,"WOODBINE, IA",United States,NaN,NaN,3YR,MUNICIPAL,...,NaN,0.0,0.0,0.0,2.0,VMC,Landing,Probable Cause,NaN,1983
3603,20001214X42063,Accident,MKC83LA050,1983-01-01,"MARYVILLE, MO",United States,NaN,NaN,78Y,RANKIN,...,NaN,0.0,0.0,0.0,1.0,VMC,Takeoff,Probable Cause,NaN,1983
3604,20001214X42018,Accident,LAX83FUG11,1983-01-01,"UPLAND, CA",United States,NaN,NaN,CCB,CABLE,...,NaN,0.0,0.0,2.0,0.0,VMC,Approach,Probable Cause,NaN,1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022,2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2022
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022,2022

In [4]:
# Keep only airplanes
df = df[df["Aircraft.Category"].str.contains("Airplane", case=False, na=False)]
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Event.Year
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,NaN,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014,1983
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,"Singapore Airlines, Ltd.",NaN,NaN,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014,1983
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011,1983
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016,1983
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016,1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022,2022
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022,2022
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022,2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022

In [5]:
#Keeping only professional builds
df = df[df["Amateur.Built"].str.upper() == "NO"] 
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Event.Year
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,NaN,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014,1983
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,"Singapore Airlines, Ltd.",NaN,NaN,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014,1983
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011,1983
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016,1983
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016,1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022,2022
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022,2022
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022,2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [6]:
df.columns.tolist()

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date',
 'Event.Year']

Adding the total number of injured and unijured passengers in order to get the total number of paasgers.
Dividing the sum of Fatl injuries and serious injuries by total number of passengers to get the serious/fatal rate.

In [7]:
#Estimate total passengers
df["Total_Passengers"] = df["Total.Fatal.Injuries"] + df["Total.Minor.Injuries"] + df["Total.Serious.Injuries"] + df["Total.Uninjured"]

# Fraction of serious/fatal injuries
df["SeriousFatal_Rate"] = (df["Total.Fatal.Injuries"] + df["Total.Serious.Injuries"]) / df["Total_Passengers"]
df

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14144\2625059595.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total_Passengers"] = df["Total.Fatal.Injuries"] + df["Total.Minor.Injuries"] + df["Total.Serious.Injuries"] + df["Total.Uninjured"]
C:\Users\Administrator\AppData\Local\Temp\ipykernel_14144\2625059595.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["SeriousFatal_Rate"] = (df["Total.Fatal.Injuries"] + df["Total.Serious.Injuries"]) / df["Total_Passengers"]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Event.Year,Total_Passengers,SeriousFatal_Rate
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014,1983,NaN,NaN
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014,1983,NaN,NaN
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011,1983,NaN,NaN
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016,1983,NaN,NaN
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016,1983,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022,2022,1.0,0.0
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022,1.0,0.0
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022,2022,1.0,0.0
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022,2022,1.0,1.0
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022,1.0,0.0

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [8]:
# Binary indicator for destruction
df["Destroyed"] = df["Aircraft.damage"].str.contains("Destroyed", case=False, na=False).astype(int)
df

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14144\3254095728.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Destroyed"] = df["Aircraft.damage"].str.contains("Destroyed", case=False, na=False).astype(int)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Event.Year,Total_Passengers,SeriousFatal_Rate,Destroyed
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014,1983,NaN,NaN,0
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014,1983,NaN,NaN,0
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011,1983,NaN,NaN,1
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016,1983,NaN,NaN,0
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016,1983,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,0.0,1.0,NaN,NaN,NaN,14-12-2022,2022,1.0,0.0,0
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022,1.0,0.0,0
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,0.0,1.0,NaN,NaN,NaN,19-12-2022,2022,1.0,0.0,0
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,0.0,0.0,VMC,NaN,NaN,23-12-2022,2022,1.0,1.0,0
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,0.0,1.0,VMC,NaN,NaN,27-12-2022,2022,1.0,0.0,0

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

Normalizing casing and white spaces
Dropping rare makes (<50 samples)
Ensuring unique identifiers for make+model

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [9]:
df["Make"] = df["Make"].str.strip().str.upper()
make_counts = df["Make"].value_counts()
valid_makes = make_counts[make_counts >= 50].index
df = df[df["Make"].isin(valid_makes)]
df = df.dropna(subset=["Model"]).copy()
# Unique identifier
df["Plane_ID"] = df["Make"] + "_" + df["Model"].fillna("")
df

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14144\2081512906.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Make"] = df["Make"].str.strip().str.upper()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Event.Year,Total_Passengers,SeriousFatal_Rate,Destroyed,Plane_ID
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,588.0,VMC,Taxi,Probable Cause,04-12-2014,1983,NaN,NaN,0,BOEING_747
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,NaN,IMC,Cruise,Probable Cause,02-05-2011,1983,NaN,NaN,1,PIPER_PA-28-140
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,4.0,VMC,Standing,Probable Cause,17-10-2016,1983,NaN,NaN,0,DE HAVILLAND_DHC-6
6760,20001214X45013,Incident,CHI84IA041,1983-11-08,"CHICAGO, IL",United States,NaN,NaN,ORD,O'HARE,...,100.0,VMC,Taxi,Probable Cause,11-06-2018,1983,NaN,NaN,0,BOEING_727-200
6806,20001214X45188,Accident,NYC84LA028,1983-11-13,"MARTHA'S VINEYARD, MA",United States,NaN,NaN,NaN,NaN,...,1.0,VMC,Climb,Probable Cause,05-05-2011,1983,NaN,NaN,0,BEECH_C35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88865,20221212106444,Accident,ERA23LA085,2022-12-12,"Knoxville, TN",United States,355745N,0835218W,DKX,KNOXVILLE DOWNTOWN ISLAND,...,1.0,VMC,NaN,NaN,15-12-2022,2022,1.0,0.0,0,CESSNA_172
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,1.0,NaN,NaN,NaN,14-12-2022,2022,1.0,0.0,0,PIPER_PA42
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,1.0,VMC,NaN,NaN,27-12-2022,2022,1.0,0.0,0,CIRRUS DESIGN CORP_SR22
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,0.0,VMC,NaN,NaN,23-12-2022,2022,1.0,1.0,0,CESSNA_R172K
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,1.0,VMC,NaN,NaN,27-12-2022,2022,1.0,0.0,0,AMERICAN CHAMPION AIRCRAFT_8GCBC

In [10]:
#Inspecting the counts
print(df["Model"].value_counts().head(20))
model_counts = df.groupby("Make")["Model"].value_counts()
print(model_counts.head(30))

Model
172          769
737          403
152          316
182          304
172S         276
PA28         273
172N         249
SR22         240
180          213
A36          181
172M         180
150          179
PA-18-150    175
PA-28-140    169
172P         143
140          117
172R         109
170B         107
PA-28-180    105
PA-28-161    102
Name: count, dtype: int64
Make            Model
AERO COMMANDER  S2R            17
                100            12
                500             5
                500S            5
                500 S           4
                500-B           4
                690             4
                100-180         3
                200D            3
                112             2
                500 B           2
                500B            2
                690A            2
                CALLAIR A 9     2
                100 180         1
                112A            1
                114B            1
                200             1
                500 - B         1
                500A            1
                560             1
                560-F           1
                560E            1
                680 E           1
                680 F           1
                680-F           1
                680E            1
                680FL           1
                685             1
                695             1
Name: count, dtype: int64

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

Some of the cleaning tasks that we will be doing for the other columns include : - Standardizing the case for the engine type
- Taking care of the white spaces
- Inconsistent labels
- some columns might be stored as string and need to be co

In [11]:
#Cleaning engine types
df["Engine.Type"] = df["Engine.Type"].astype(str).str.strip().str.upper()
print(df["Engine.Type"].value_counts().head(10))

Engine.Type
RECIPROCATING      12835
NAN                 3214
TURBO PROP           931
TURBO FAN            701
UNKNOWN              105
TURBO JET             71
GEARED TURBOFAN       12
TURBO SHAFT            9
UNK                    1
Name: count, dtype: int64

In [12]:
#Cleaning weather conditions
df["Weather.Condition"] = df["Weather.Condition"].astype(str).str.strip().str.upper()
print(df["Weather.Condition"].value_counts().head(10))

Weather.Condition
VMC    14295
NAN     2417
IMC      905
UNK      262
Name: count, dtype: int64

In [13]:
#Number of engines
df["Number.of.Engines"] = pd.to_numeric(df["Number.of.Engines"], errors="coerce")
print(df["Number.of.Engines"].value_counts().sort_index())

Number.of.Engines
0.0        5
1.0    13222
2.0     2470
3.0       26
4.0       67
Name: count, dtype: int64

In [14]:
#Purpose of the flight
df["Purpose.of.flight"] = df["Purpose.of.flight"].astype(str).str.strip().str.upper()
print(df["Purpose.of.flight"].value_counts().head(20))

Purpose.of.flight
PERSONAL                     9844
NAN                          3047
INSTRUCTIONAL                2410
AERIAL APPLICATION            724
BUSINESS                      409
UNKNOWN                       303
POSITIONING                   269
SKYDIVING                     157
AERIAL OBSERVATION            147
OTHER WORK USE                121
BANNER TOW                     86
FLIGHT TEST                    73
FERRY                          72
EXECUTIVE/CORPORATE            65
GLIDER TOW                     29
PUBLIC AIRCRAFT - FEDERAL      28
PUBLIC AIRCRAFT                27
PUBLIC AIRCRAFT - STATE        21
AIR RACE SHOW                  15
FIREFIGHTING                   12
Name: count, dtype: int64

In [15]:
#Broad phase of flight
df["Broad.phase.of.flight"] = df["Broad.phase.of.flight"].astype(str).str.strip().str.upper()
print(df["Broad.phase.of.flight"].value_counts().head(15))

Broad.phase.of.flight
NAN            15427
LANDING         1110
TAKEOFF          425
CRUISE           238
APPROACH         210
MANEUVERING      127
TAXI              99
GO-AROUND         81
DESCENT           62
CLIMB             52
STANDING          35
UNKNOWN           11
OTHER              2
Name: count, dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [16]:
na_counts = df.isna().sum().sort_values(ascending=False)
na_counts

Schedule                  15740
Air.carrier                9431
Airport.Code               6231
Airport.Name               6125
Report.Status              3785
SeriousFatal_Rate          3360
Total_Passengers           2620
Total.Serious.Injuries     2458
Total.Fatal.Injuries       2386
Total.Minor.Injuries       2223
Number.of.Engines          2089
Longitude                  1901
Latitude                   1898
Aircraft.damage            1064
Publication.Date            788
Injury.Severity             717
Total.Uninjured             587
FAR.Description             344
Registration.Number         164
Location                      4
Country                       1
Broad.phase.of.flight         0
Event.Year                    0
Weather.Condition             0
Destroyed                     0
Event.Id                      0
Engine.Type                   0
Purpose.of.flight             0
Investigation.Type            0
Amateur.Built                 0
Model                         0
Make                          0
Aircraft.Category             0
Event.Date                    0
Accident.Number               0
Plane_ID                      0
dtype: int64

To correctly determine which columns to drop, we will find the %age of missing values relative to each column and drop columns that contain < 40% missing values.

In [17]:
na_percent = (df.isna().sum() / len(df)) * 100
na_percent

Event.Id                   0.000000
Investigation.Type         0.000000
Accident.Number            0.000000
Event.Date                 0.000000
Location                   0.022373
Country                    0.005593
Latitude                  10.615806
Longitude                 10.632586
Airport.Code              34.850942
Airport.Name              34.258068
Injury.Severity            4.010291
Aircraft.damage            5.951116
Aircraft.Category          0.000000
Registration.Number        0.917277
Make                       0.000000
Model                      0.000000
Amateur.Built              0.000000
Number.of.Engines         11.684099
Engine.Type                0.000000
FAR.Description            1.924045
Schedule                  88.036244
Purpose.of.flight          0.000000
Air.carrier               52.749035
Total.Fatal.Injuries      13.345265
Total.Serious.Injuries    13.747972
Total.Minor.Injuries      12.433581
Total.Uninjured            3.283181
Weather.Condition          0.000000
Broad.phase.of.flight      0.000000
Report.Status             21.170088
Publication.Date           4.407405
Event.Year                 0.000000
Total_Passengers          14.654063
SeriousFatal_Rate         18.792997
Destroyed                  0.000000
Plane_ID                   0.000000
dtype: float64

In [18]:
#Drop columns with more than 40% NaNs
threshold = 0.4
df = df.loc[:, df.isna().mean() < threshold]
print("Remaining columns:", df.columns.tolist())
print("Shape after dropping:", df.shape)

Remaining columns: ['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Purpose.of.flight', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date', 'Event.Year', 'Total_Passengers', 'SeriousFatal_Rate', 'Destroyed', 'Plane_ID']
Shape after dropping: (17879, 34)

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [19]:
df.to_csv("aviation_accidents_clean.csv", index=False)